
let toolbarOptions = [
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
  [{ 'font': [] }],
  ['bold', 'italic', 'underline', 'strike'],
  [{ 'size': ['small', false, 'large', 'huge'] }],
  ['blockquote', 'code-block'],
  [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'align': [] }],
  [{ 'indent': '-1' }, { 'indent': '+1' }, { 'direction': 'rtl' }],
  [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  ['link', 'image'],
  ['clean']                                         // remove formatting button
];

//Sets up the quill editor in the element with the id of "editor"
quill = new Quill('#editor', {
  modules: {
    toolbar: toolbarOptions
  },
  theme: 'snow'
});

const initialContent = quill.getContents();


//new user redirect
let pageVisits = JSON.parse(localStorage.getItem('pageVisits'));

function redirectToInfo() {
  window.location = "intro.html";
}

function redirectNewUser() {
  if (pageVisits == null) {
    pageVisits += 1;
    localStorage.setItem("pageVisits", pageVisits);
    redirectToInfo();
  }
}

//global variables
let editingField = document.querySelector(".ql-editor");
let notesListContainer = document.querySelector('.saved-notes-list');
let saveNoteBtn = document.querySelector('.save-note-btn');
let newNoteButton = document.querySelector(".new-note-button");
let starButton = document.querySelector('#starred-button')
let currentView = 'allNotes'

//function that opens the editor
newNoteButton.addEventListener("click", function () {
  document.querySelector(".toolbar-and-editor-container").classList.remove("hidden");
  quill.setContents(initialContent);
  console.log("Hej");
});

//unique identifyer for each note to act as a local storage key that is taken from local storage
let notesNumber = JSON.parse(localStorage.getItem('notesNumber'));


//creating a note
  function createNote() {
    //creates one list item in the saved notes div containing all of the html generated by the editor
    const buttonId = `favorite-button-${notesNumber}`
    //data-noteid is used in bindFavoriteButtons function
    let note = `<li data-noteid=${notesNumber} class="note">
                  ${editingField.innerHTML}<span>${date()}</span>
                  <button class="favorite-toggle" id="${buttonId}">
                    <svg
                      aria-hidden="true"
                      focusable="false"
                      data-prefix="fas"
                      data-icon="star"
                      class="svg-inline--fa fa-star fa-w-18"
                      role="img"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 576 512">
                      <path
                        stroke="black" stroke-width="20" stroke-linecap="round"
                        d="M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z"
                      ></path>
                    </svg>
                  </button>
                </li>`;
    notesListContainer.innerHTML += note;
    //saves the note html as a JSON string in Local Storage
    localStorage.setItem(notesNumber, JSON.stringify(note))
    bindFavoriteButtons()
  }

  function bindFavoriteButtons() {
    //get all notes
    const allNotes = document.querySelectorAll(".note")
    //for each note 
    allNotes.forEach(function(note){
      //bind click event for all favorite buttons
      note.querySelector(".favorite-toggle").addEventListener("click",function(){
        const noteId = note.dataset.noteid
        toggleFavorite(noteId)
      })
    })
  }

  function toggleFavorite(noteId){
    //get note from localStorage
    const listItem = document.querySelector(`[data-noteid="${noteId}"]`)
    //toggle favorit class on listItem
    listItem.classList.toggle("favorite")
    //saving in localStorage
    localStorage.setItem(noteId, JSON.stringify(listItem.outerHTML))
  }

//saving a note
  saveNoteBtn.onclick = function saveNote(){
    
    //select the first element in the editing field
    let firstElement = editingField.firstChild;
    //only creates a note if first element is a heading(h1, h2...h6) and it is not empty
    if (firstElement.tagName.startsWith('H') && firstElement.textContent.trim() != "") {
      //the id increases by 1 for each created note
      notesNumber += 1;
      //saves the number in local storage for access
      localStorage.setItem('notesNumber', notesNumber);
      //creates the note
      createNote();
      //closes the editor
      document.querySelector(".toolbar-and-editor-container").classList.add("hidden");
    } else alert("Please add a heading at the begining of your note, it will act as the note\'s title");
  }


//loading notes from local storage
function loadNotes() {

  for (i = 1; i <= notesNumber; i++) {
    //console.log(i);
    //console.log(localStorage.getItem(i));
    let note = JSON.parse(localStorage.getItem(i));
    notesListContainer.innerHTML += note;
  }
}

// NOTES LIST CONTAINER SHOW:
function renderCurrentView() {
  notesListContainer.innerHTML = '';
// show all notes
    if (currentView == 'allNotes'){
      renderAllNotes()
    }
// show favorit notes
    else if (currentView == 'favorites'){
      renderFavorites()
    }
    bindFavoriteButtons()
}


function renderAllNotes(){
  loadNotes()
}

function renderFavorites(){
  loadNotes()
  //get all non-favorite-listItem
  const nonFavoriteItems = notesListContainer.querySelectorAll('.note:not(.favorite)')
  nonFavoriteItems.forEach(function(nonFavoriteItem){
      nonFavoriteItem.remove()
  })
}

function bindStarButton(){
  starButton.addEventListener('click', function(){
    //when starButton is selected, it gets gold
    starButton.classList.toggle('selected')
    //when current view is "favorites", view insted all notes on click"
    if (currentView == 'favorites'){
      currentView = 'allNotes'
    }
    //when current view is on all notes, view insted "favorites notes on click"
    else if (currentView == 'allNotes'){
      currentView = 'favorites'
    }
    renderCurrentView()
  })
  
}

document.addEventListener('DOMContentLoaded', e => {
  renderCurrentView();
  bindFavoriteButtons();
  bindStarButton();
})



/* ADDITIONAL FUNCTIONS NOT IMPLEMENTED */
/* Date Function */
function date() {
  let now = new Date();

  let dd = now.getDate();
  let m = now.getMonth() + 1;
  let yyyy = now.getFullYear();
  let hh = now.getHours();
  let mm = now.getMinutes();
  let ss = now.getSeconds();

  if (dd < 10) {
    dd = `0${dd}`;
  }
  if (m < 10) {
    m = `0${m}`;
  }
  if (hh < 10) {
    hh = `0${hh}`;
  }
  if (mm < 10) {
    mm = `0${mm}`;
  }
  if (ss < 10) {
    ss = `0${ss}`;
  }

  now = `${dd}/${m}/${yyyy} ${hh}:${mm}`;
  return now;
}



/* Read only mode */
// To turn the editor into "read-only-mode" - the toolbar is hidden and the content of the editor is non-editable. When clcked on again, it is made into "edit-mode" and the toolbar is shown again.
// Activate function from e.g. a button with a event listener that activates the function
// Also need to create a class of "hide-toolbar" with a "display: none; property"
function editToggle(e) {
  // Add the class "edit-button" to the html element that activates this function
  if (!e.target.classList.contains('edit-button')) {
    return;
  }

  const editor = document.querySelector('.ql-editor');
  const toolbar = document.querySelector('.ql-toolbar.ql-snow');

  if (editor.getAttribute('contenteditable') === 'true') {
    // makes the editor non-editable
    editor.setAttribute('contenteditable', false);
    // adds the class "hide-toolbar" containing a "dsplay: none;" to hide the toolbar
    toolbar.classList.toggle('hide-toolbar');
  } else {
    // the opposite
    editor.setAttribute('contenteditable', true);
    toolbar.classList.toggle('hide-toolbar');
  }
}




/* // EXAMPLE OF TOOLBAR CUSTOMIZATION
var toolbarOptions = [
  [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
  [{ 'font': [] }],
  ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
  [{ 'size': ['small', false, 'large', 'huge'] }],  // custom dropdown
  ['blockquote', 'code-block'],
  [{ 'list': 'ordered' }, { 'list': 'bullet' }, { 'align': [] }],
  [{ 'indent': '-1' }, { 'indent': '+1' }, { 'direction': 'rtl' }],          // outdent/indent
  [{ 'script': 'sub' }, { 'script': 'super' }],      // superscript/subscript
  [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
  ['link', 'image'],
  ['clean']                                         // remove formatting button
]; */

// IN ORDER TO WORK THE FOLLOWING NEEDS TO BE WRITTEN WHEN INITIALIZING THE EDITOR
/*
quill = new Quill('#editor', {
    modules: {
        toolbar: toolbarOptions
    },
    theme: 'snow'
});
*/